marketing:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5555
      user: dev
      password: dev
      dbname: multi_project
      schema: public
      threads: 1
