bigquery_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: dbt_temporal_example
      threads: 4
      timeout_seconds: 300
      location: US
